### ISSUE TITLE
typo checkGameOverDiagonalBackslah and checkGameOverDiagonalForwardslah

### ISSUE THREAD

**Issue by Isitar** [Akratash/viergewinnt#1]
typo in method name: `checkGameOverDiagonalBackslah`

https://github.com/Akratash/viergewinnt/blob/3206640ec5fe0e26efc8e0f0971f4a5431c6db80/ch.akratash.viergewinnt.model/src/ch/akratash/viergewinnt/model/Board.java#L93

https://github.com/Akratash/viergewinnt/blob/3206640ec5fe0e26efc8e0f0971f4a5431c6db80/ch.akratash.viergewinnt.model/src/ch/akratash/viergewinnt/model/Board.java#L99

do not forget to refactor calls to method (L64 and L65)

**Comment by eulor** [comment]
Rename methods with Refactor-Function (Shift+Ctrl+R or Right-Click on Method->Refactor->Rename) in Eclipse
